services:
  server:
    build: ./axum_server
    hostname: axum-server
    container_name: http-server
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql://root:root@mariadb:3306/mysql
      RUST_BACKTRACE: full
      #DNS_SERVER: 127.0.0.11:53
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:latest
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped